### ISSUE TITLE
Recommend to correct the wiki tutorial

### ISSUE THREAD

**Issue by maitrungduc1410** [michaelbukachi/django-vuejs-tutorial#4]
I'm just followed how to integrate VueJS with Django in tab Wiki. In the final when run the app it always said cannot find template module. Then I found that you missed the step to set default directory for template in `settings.py`. The TEMPLATES should be like this:
```
TEMPLATES = [
    {
        ...
        'DIRS': [os.path.join(BASE_DIR, 'myapp/templates')],
        ...
    },
]
```
Can you check and correct it if I'm right, for other people come to your tutorial after me no be confused :)

**Comment by michaelbukachi** [comment]
@maitrungduc1410 Django by default will set `app/templates` as the default directory of templates for `app` is the django app so you don't have to specify it explicitly. Can you please specify which Django version you are using?

**Comment by xrafael** [comment]
Thanks for the tutorial. I could follow it quite smoothly. However I had to do some fixes to make it work, a part from the  fix proposed by @maitrungduc1410, which were: 
- Required to install "vue-template-compiler", "vue-resource"
- In" webpack.config"  replaced "loaders" by "rules" 
- In "webpack.config.js" added:
 var VueLoaderPlugin = require('vue-loader/lib/plugin')

Hope it helps!
plugins: [
        ...
        new VueLoaderPlugin(),
],

**Comment by adamkusmirek** [comment]
Having just gone trough your tutorial, I can confirm the npm additions suggested by @xrafael 
I had to install `vue-template-compiler`, `babel-loader` and `webpack-bundle-tracker`.

Also, I suggest mentioning that one should set the 'mode' option in webpack.config.js

**Comment by michaelbukachi** [comment]
@adamkusmirek what node version are you using?

**Comment by michaelbukachi** [comment]
@adamkusmirek @xrafael I've updated the wiki and the dependencies accordingly. I will now close this issue.
