### ISSUE TITLE
Please change the spelling - mkdir -p assets/js/componets --> components 

### ISSUE THREAD

**Issue by amreshgiri-coditas** [michaelbukachi/django-vuejs-tutorial#5]
This might save some time for people who like to experiment and want to save some time by copying code. I wasted a few minutes due to the spelling mistake because I copied that simple command without realising the spelling mistake which turned out to be a disaster later. I request you to update the wiki so that no one else has to go through this.

**Comment by michaelbukachi** [comment]
Thanks. I've updated the wiki.
