### ISSUE TITLE
missing webpack-bundle-tracker in wiki guide

### ISSUE THREAD

**Issue by MohammadRafik** [michaelbukachi/django-vuejs-tutorial#7]
Hello
The wiki guide has a command for installing all the node-modules

`npm install --save-dev axios bootstrap-sass jquery node-sass sass-loader vue webpack webpack-cli  @babel/core @babel/plugin-transform-runtime @babel/preset-env @babel/runtime babel-loader babel-preset-es2015 babel-preset-stage-0 css-loader style-loader vue-loader vue-hot-reload-api vue-template-compiler`

this command is missing webpack-bundle-tracker

**Comment by michaelbukachi** [comment]
Thanks for that. I've made the correction.
