### ISSUE TITLE
Wiki tutorial fix for Vue ReferenceError

### ISSUE THREAD

**Issue by ZviBaratz** [michaelbukachi/django-vuejs-tutorial#9]
Hi,

Thank you for the detailed tutorial! 
I wanted to PR a tiny fix but it seems it's a bit complicated for Wiki pages, so I just wanted to let you know I got a ReferenceError for Vue that was fixed by adding `window.Vue = Vue;` in `index.js`.

So `index.js` now looks like this:
```
window.$ = window.jQuery = require('jquery');
require('bootstrap-sass');

import Vue from 'vue';
import Demo from "./components/Demo.vue";

window.Vue = Vue;
const app = new Vue({
    el: '#app',
    components: {
        Demo
    }
});
```

Hope this helps and thank you again,
Zvi

**Comment by michaelbukachi** [comment]
Awesome! You can still do a pull request to update the code. I'll make changes to the Wiki

**Comment by ZviBaratz** [comment]
Done. I also added [vuetify](https://vuetifyjs.com/en/) integration in [my fork](https://github.com/ZviBaratz/django-vuejs-tutorial) ( after PR #10 ). It mostly consists of adding the required packages and webpack loaders, as well as adding a [TreeView](https://vuetifyjs.com/en/components/treeview) to see that it works when running the server. 
Let me know if you'd like for me to PR that as well, I wasn't sure whether it fits the purposes of this repo or not.
